export default {
    REQUEST_TODOS: 'REQUEST_TODOS',
    RECEIVE_TODOS: 'RECEIVE_TODOS',
    DONE_TODO: 'DONE_TODO',
    RM_TODO: 'RM_TODO',
    START_ADD_TODO: 'START_ADD_TODO',
    REQUEST_TODO: 'REQUEST_TODO',
    RECEIVE_TODO: 'RECEIVE_TODO',
    UPDATING_TODO: 'UPDATING_TODO',
    UPDATED_TODO: 'UPDATED_TODO',
    END_EDIT_TODO: 'END_EDIT_TODO'
};

