export default {
    REQUEST_CATEGORIES: 'REQUEST_CATEGORIES',
    RECEIVE_CATEGORIES: 'RECEIVE_CATEGORIES',
    START_ADD_CATEGORY: 'START_ADD_CATEGORY',
    UPADATING_ADD_CATEGORY: 'UPADATING_ADD_CATEGORY',
    UPADATED_ADD_CATEGORY: 'UPADATED_ADD_CATEGORY',
    UPDATING_EDIT_CATEGORY: 'UPDATING_EDIT_CATEGORY',
    UPDATED_EDIT_CATEGORY: 'UPDATED_EDIT_CATEGORY',
    UPDATING_RM_CATEGORY: 'UPDATING_RM_CATEGORY',
    UPDATED_RM_CATEGORY: 'UPDATED_RM_CATEGORY',
    ABORT_ADD_CATEGORY: 'ABORT_ADD_CATEGORY'
};